<?php
/**
 * Copyright © element119. All rights reserved.
 * See LICENCE.txt for licence details.
 */
declare(strict_types=1);

use Element119\MagewireCart\Magewire\Action\Coupon as CartCouponMagewireComponent;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var CartCouponMagewireComponent $couponComponent */
$couponComponent = $block->getMagewire();
?>
<div x-data
     class="flex flex-col justify-center gap-2 sm:flex-row md:justify-start">
    <input type="text"
           id="coupon_code"
           name="coupon_code"
           class="form-input text-center border-background-dark md:text-left"
           placeholder="<?= $escaper->escapeHtmlAttr(__('Enter discount code')); ?>"
           wire:model.defer="couponCode"
           wire:keydown.enter="apply"
           :disabled="$wire.isCouponApplied"
           :class="{'text-gray-500': $wire.isCouponApplied}"/>
    <button type="submit"
            @click.prevent="$wire.isCouponApplied ? $wire.remove() : $wire.apply()"
            value="<?= $escaper->escapeHtmlAttr(__('Apply Coupon Code')); ?>"
            class="btn btn-primary justify-center md:text-sm lg:text-base">
        <span>
            <?= $escaper->escapeHtml($couponComponent->isCouponApplied
                ? __('Cancel Coupon')
                : __('Apply Discount')
            ); ?>
        </span>
    </button>
</div>
