<?php
/**
 * Copyright © element119. All rights reserved.
 * See LICENCE.txt for licence details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>
<div class="w-full lg:w-1/4 float-left lg:float-right lg:order-2 top-0 lg:sticky">
    <div class="flex pb-3 my-2 border-b-2 border-gray-300 flex-col">
        <h2 class="w-full text-2xl text-center text-gray-900 title-font font-base md:text-left">
            <?= $escaper->escapeHtml(__('Summary')); ?>
        </h2>
    </div>
    <?= $block->getChildHtml(); ?>
</div>
